### ISSUE TITLE
The app is crashing if tracker URI contains Unicode symbols

### ISSUE THREAD

**Issue by edtechd** [feross/magnet-uri#13]
encodeURIComponent causing an exception if the function argument contains Unicode symbols

URIError: URI malformed
    at encodeURIComponent (native)
    at /home/nodejsuser/offcloud/server/downloader/node_modules/parse-torrent/node_modules/magnet-uri/index.js:117:17
    at Array.forEach (native)
    at /home/nodejsuser/offcloud/server/downloader/node_modules/parse-torrent/node_modules/magnet-uri/index.js:112:14
    at Array.forEach (native)
    at Function.magnetURIEncode [as toMagnetURI] (/home/nodejsuser/offcloud/server/downloader/node_modules/parse-torrent/node_modules/magnet-uri/index.js:110:6)

I think it makes sense to filter/escape value before encodeURIComponent, or catch the exception

**Comment by feross** [comment]
Unicode is handled correctly. This error is caused by an invalid Unicode sequence.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent): 

> Note that an URIError will be thrown if one attempts to encode a surrogate which is not part of a high-low pair.
