### ISSUE TITLE
Support for webseeding property (ws=)

### ISSUE THREAD

**Issue by grunjol** [feross/magnet-uri#6]
Although some consider the (acceptable source) as=<URL> for web seeding source, the parameter ws=<URL> should be used as url-list counterpart in magnet case. 

I think its not a big change. 

Some references

Transmission magnet parser:
https://trac.transmissionbt.com/browser/trunk/libtransmission/magnet.c#L169

French wikipedia (OK, maybe not THE source)
http://fr.wikipedia.org/wiki/Magnet_(standard)

**Comment by feross** [comment]
Thanks for pointing out the existence of "ws". The only support we currently have for "as" is we decode URLs. We should decode URLs in "ws" as well. And perhaps even merge the "as" and "ws" lists into a `urlList` property on the returned object.

**Comment by grunjol** [comment]
Not sure for *as*, but *ws* i think its a good idea.
I was reworking this https://github.com/feross/webtorrent/pull/177 PR and found I have no urls when parsing the magnet

**Comment by feross** [comment]
Released as 4.2.0.

**Comment by andreekeberg** [comment]
Is there any difference in how `as` and `ws` are treated when downloading?

**Comment by feross** [comment]
@andreekeberg Please open a new issue rather than commenting in an issue that is 4 years old. Thanks.
